id: d2c8368679314330ad68defd77809f80
initial_creation_type: ocr
source_metadata:
  volumes:
    c86ddc31c67d44a6b0ac7511d6ccde57:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
