id: D7C7B333F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:37:32+00:00'
last_modified: '2022-06-07T07:13:35.303944+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    846e:
      image_group_id: I1PD95846
      title: ཆོས་ཀྱི་སྐུ་ལ་གནས་པའི་ཡོན་ཏན་ཐུན་མོང་མ་ཡིན་པ་ལ་བསྟོད་པ།
      total_pages: 1539
      order: 1
      base_file: 846e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
